/**
 * Precanned test profiles for the book pipeline.
 * Each profile covers a different combination of age, problem, style, and appearance.
 */

import type { BatchProfile } from './bookBatchValidation';

export const PRECANNED_PROFILES: BatchProfile[] = [
  {
    childName: 'Zosia',
    ageBracket: '3-5',
    gender: 'girl',
    problemId: 'fear_of_dark',
    hairColor: 'blond',
    hairStyle: 'dlugie_proste',
    eyeColor: 'niebieskie',
    skinTone: 'jasna',
    outfit: 'sukienka_motyle',
    glasses: false,
    chosenStyle: 'A',
  },
  {
    childName: 'Kuba',
    ageBracket: '6-8',
    gender: 'boy',
    problemId: 'tantrums',
    hairColor: 'braz',
    hairStyle: 'krotkie_proste',
    eyeColor: 'brazowe',
    skinTone: 'srednia',
    outfit: 'bluza_dinozaur',
    glasses: false,
    chosenStyle: 'B',
  },
  {
    childName: 'Maja',
    ageBracket: '3-5',
    gender: 'girl',
    problemId: 'shyness',
    hairColor: 'rudy',
    hairStyle: 'koki',
    eyeColor: 'zielone',
    skinTone: 'smietankowa',
    outfit: 'bluza_jednorozec',
    glasses: false,
    chosenStyle: 'A',
  },
  {
    childName: 'Tomek',
    ageBracket: '9+',
    gender: 'boy',
    problemId: 'screen_addiction',
    hairColor: 'ciemny_braz',
    hairStyle: 'krotkie_falowane',
    eyeColor: 'piwne',
    skinTone: 'srednia',
    outfit: 'bluza_rakieta',
    glasses: true,
    chosenStyle: 'A',
  },
  {
    childName: 'Lena',
    ageBracket: '6-8',
    gender: 'girl',
    problemId: 'new_sibling',
    hairColor: 'jasny_braz',
    hairStyle: 'kucyk',
    eyeColor: 'szare',
    skinTone: 'jasna',
    outfit: 'bluza_kwiaty',
    glasses: false,
    chosenStyle: 'B',
  },
  {
    childName: 'Olek',
    ageBracket: '3-5',
    gender: 'boy',
    problemId: 'picky_eating',
    hairColor: 'czarny',
    hairStyle: 'krotkie_proste',
    eyeColor: 'brazowe',
    skinTone: 'ciemna',
    outfit: 'ogrodniczki',
    glasses: false,
    chosenStyle: 'A',
  },
];
