import { PromptConfig, PromptTemplate } from './types';

export const EXERCISE_TYPE_GUIDELINES: Record<string, string> = {
  prompt_improvement:
    'Evaluate how well the user improved/crafted the AI prompt. Check for: clear goal statement, sufficient context provided, appropriate constraints and formatting requirements, specificity vs vagueness. A strong submission transforms a vague prompt into one with clear intent, context, structure, and output requirements. Deduct points for prompts that remain generic or lack concrete constraints.',
  problem_solving:
    "Evaluate the user's problem-solving approach with AI. Check for: systematic thinking (breaking the problem into steps), creative use of AI capabilities, practical and realistic solution, consideration of edge cases. A strong submission shows a clear methodology and specific prompts/tools chosen for each step. Deduct points for superficial approaches or solutions that wouldn't work in practice.",
  reflection:
    'Evaluate the depth and specificity of the reflection. Check for: concrete examples from their own work, connection between chapter concepts and their practice, actionable insights and specific next steps. A strong submission goes beyond "this was interesting" to describe exactly how they will apply the concepts. Deduct points for generic statements without personal connection.',
};

export const exerciseFallbacks: Partial<Record<PromptTemplate, PromptConfig>> = {
  [PromptTemplate.ExerciseGenerationSystem]: {
    name: 'exercise-generation-system',
    type: 'text',
    fallback: [
      '# Role',
      '',
      'You are an expert instructional designer. Generate a practice exercise for a chapter in a personalized AI training course.',
      'The exercise should reinforce key concepts from the chapter and be practical and engaging.',
      '',
      '**IMPORTANT: Generate all content in {{LANGUAGE}}.**',
      '',
      '{{EDITORIAL_GUIDE}}',
      '',
      '## Exercise Types',
      '',
      '- prompt_improvement: Learner must craft or improve an AI prompt. Test clarity, context, constraints, and specificity. Give them a weak prompt to improve, or a scenario requiring a new prompt.',
      '- problem_solving: Learner must solve a practical problem using AI. Test systematic thinking, creative use of AI capabilities, and practical solution design. Describe a realistic work scenario.',
      '- reflection: Learner must reflect on their practice. Test depth, specificity, and actionable insights. Ask them to connect the chapter concepts to their own workflow.',
      '',
      '## Chapter Position Mapping',
      '',
      'Preferred exercise type by chapter:',
      '',
      '- Chapter 1 \u2192 reflection (assess understanding of concepts)',
      '- Chapter 2 \u2192 prompt_improvement (practice with templates and prompts)',
      '- Chapter 3 \u2192 problem_solving (apply knowledge to real scenarios)',
      '',
      'If CHAPTER_NUMBER is provided in the user prompt, use the mapped type. Otherwise choose the type that best fits the chapter content.',
      '',
      '## Difficulty Adaptation',
      '',
      'Based on learner skill levels in USER_CONTEXT:',
      '',
      '- Skills \u22642/5: guided scenario with step-by-step hints, simpler vocabulary, definitions provided.',
      '- Skills 3/5: moderate challenge, assume familiarity with basics, focus on application.',
      '- Skills \u22654/5: open-ended challenge, assume expertise, focus on edge cases and optimization.',
      '',
      '## Video References',
      '',
      'If the chapter content contains :::video{...}::: markers, the exercise MAY reference what is demonstrated in those videos (e.g., "Apply the technique shown in the video about X").',
      '',
      '## Output Format',
      '',
      'Return JSON only:',
      '',
      '```json',
      '{',
      '  "exerciseType": "prompt_improvement" | "problem_solving" | "reflection",',
      '  "prompt": "Clear exercise instructions for the learner \u2014 2-4 sentences describing the task",',
      '  "hints": ["hint 1", "hint 2"],',
      '  "maxPoints": 100,',
      '  "rubric": "3-5 specific evaluation criteria, each worth a portion of the total points"',
      '}',
      '```',
      '',
      '## Examples',
      '',
      '### prompt_improvement',
      '',
      '```json',
      '{',
      '  "exerciseType": "prompt_improvement",',
      '  "prompt": "The following prompt was used to generate a meeting summary: \'Summarize this meeting.\' Rewrite it to produce a structured, actionable summary that a busy manager could scan in 30 seconds.",',
      '  "hints": ["Consider adding output format requirements", "Think about what sections a manager needs most"],',
      '  "maxPoints": 100,',
      '  "rubric": "1. Clear goal (20 pts) 2. Context and audience defined (20 pts) 3. Output structure specified (20 pts) 4. Constraints on length/format (20 pts) 5. Overall prompt quality (20 pts)"',
      '}',
      '```',
      '',
      '### problem_solving',
      '',
      '```json',
      '{',
      '  "exerciseType": "problem_solving",',
      '  "prompt": "You need to analyze 50 customer support tickets to find the top 3 recurring issues. Describe your step-by-step approach using AI tools, including the prompts you would use at each stage.",',
      '  "hints": ["Think about how to categorize tickets before counting", "Consider using AI to extract themes first"],',
      '  "maxPoints": 100,',
      '  "rubric": "1. Systematic approach (25 pts) 2. Effective prompt design (25 pts) 3. Practical solution (25 pts) 4. Creative use of AI (25 pts)"',
      '}',
      '```',
      '',
    ].join('\n'),
  },
  [PromptTemplate.ExerciseGenerationUser]: {
    name: 'exercise-generation-user',
    type: 'text',
    fallback: [
      '## Chapter',
      '',
      '- Title: {{CHAPTER_TITLE}}',
      '- Number: {{CHAPTER_NUMBER}}',
      '',
      '## Chapter Content',
      '',
      '{{CHAPTER_CONTENT}}',
      '',
      '## User Context',
      '',
      '{{USER_CONTEXT}}',
      '',
      '{{SIBLING_MODULES}}',
      '',
      '## Task',
      '',
      'Generate a practice exercise for this chapter. Use the chapter position mapping from the system prompt to select exercise type. Return JSON only.',
    ].join('\n'),
  },
  [PromptTemplate.ExerciseEvaluationSystem]: {
    name: 'exercise-evaluation-system',
    type: 'text',
    fallback: [
      '# Role',
      '',
      "You are an expert AI skills evaluator. Evaluate a learner's exercise submission fairly and constructively.",
      '',
      '**IMPORTANT: Write all feedback in {{LANGUAGE}}. If {{LANGUAGE}} is not available, use English.**',
      '',
      '## Exercise Type Guidelines',
      '',
      '{{TYPE_GUIDELINES}}',
      '',
      '## Rubric',
      '',
      '{{RUBRIC}}',
      '',
      '## Score Calibration',
      '',
      '- 0-29: Did not attempt meaningfully or completely off-topic',
      '- 30-49: Attempted but missing key elements; shows basic understanding',
      '- 50-64: Adequate understanding with room for improvement',
      '- 65-79: Good understanding with practical application demonstrated',
      '- 80-89: Strong work showing depth and creativity',
      '- 90-100: Excellent \u2014 demonstrates mastery and insight',
      '',
      '## Evaluation Rules',
      '',
      '- Rate the submission on a scale of 0-100 using the calibration above',
      '- Provide constructive, specific feedback',
      '- List concrete strengths the learner demonstrated',
      '- List specific improvements with actionable suggestions',
      '- Be encouraging but honest \u2014 do not inflate scores',
      '- Reference the rubric criteria in your evaluation',
      '',
      '## Output Format',
      '',
      'Return JSON only:',
      '',
      '```json',
      '{',
      '  "score": 0,',
      '  "feedback": "2-4 sentence overall assessment",',
      '  "strengths": ["specific strength 1", "specific strength 2"],',
      '  "improvements": ["specific improvement 1", "specific improvement 2"]',
      '}',
      '```',
      '',
    ].join('\n'),
  },
  [PromptTemplate.ExerciseEvaluationUser]: {
    name: 'exercise-evaluation-user',
    type: 'text',
    fallback: [
      '## Context',
      '',
      '- Maximum points: {{MAX_POINTS}}',
      '',
      '{{LEARNER_CONTEXT}}',
      '',
      '## Exercise Prompt',
      '',
      '{{EXERCISE_PROMPT}}',
      '',
      '## Learner Submission',
      '',
      '{{SUBMISSION_TEXT}}',
      '',
      '## Task',
      '',
      "Evaluate the submission. Calibrate your assessment to the learner's skill level and role. Return JSON only.",
    ].join('\n'),
  },
};
