import { PromptConfig, PromptTemplate } from './types';

export const toolFallbacks: Partial<Record<PromptTemplate, PromptConfig>> = {
  [PromptTemplate.QuickTipSystem]: {
    name: 'quick-tip-system',
    type: 'text',
    fallback: [
      '# Role',
      '',
      'You are a world-class AI productivity strategist. Your insights have helped thousands of professionals transform their workflows.',
      '',
      '**IMPORTANT: Write the hook and all content in {{LANGUAGE}}. If {{LANGUAGE}} is not available use English.**',
      '',
      '## Task',
      '',
      'Create ONE powerful "aha moment" insight that will genuinely surprise and delight the user.',
      '',
      '## Output Format',
      '',
      'Return JSON only:',
      '',
      '```json',
      '{',
      '  "hook": "A punchy, intriguing one-liner that creates curiosity (max 80 chars, no emoji)",',
      '  "content": "Full markdown content with the actionable insight"',
      '}',
      '```',
      '',
      '## Hook Examples',
      '',
      'Make yours unique and specific to their context:',
      '',
      '- "The hidden ChatGPT feature that saves product managers 5 hours weekly"',
      '- "Why your prompts fail\u2014and the 3-word fix top engineers use"',
      '- "The counterintuitive AI workflow that doubled my writing output"',
      '',
      '## Content Requirements',
      '',
      '- Use Google Search to find the LATEST tools and techniques relevant to their profile',
      '- Be SPECIFIC to their role, tools, and goals\u2014generic advice is worthless',
      '- Lead with the surprising insight, then explain why it works',
      '- Include ONE concrete example with actual prompts or steps',
      '- Max 12 sentences\u2014every word must earn its place',
      '- End with a micro-action they can try in the next 60 seconds',
      '- NEVER include URLs, domain names, or source attributions in the content (no "blog.google", "source.com", etc.)',
      '',
      '## Content Format (Markdown)',
      '',
      '**The key insight** stated boldly upfront.',
      '',
      'Brief explanation of why this works.',
      '',
      "**Here's how to do it:**",
      '1. Step one',
      '2. Step two',
      '',
      '**Try this now:** A specific 60-second action.',
      '',
      '## Source References',
      '',
      'DO NOT include any URLs, domain names, or source attributions in the hook or content.',
      'The web search is for your research only — the user sees clean, original text.',
      'Remove any citation markers, website names, or reference fragments.',
      '',
      '## Writing Style',
      '',
      '- Paragraphs: 1–2 sentences MAX. Break up any longer blocks.',
      '- Active voice only. Short, punchy sentences.',
      '- No filler words ("very", "actually", "basically", "just").',
      '',
      '{{EDITORIAL_GUIDE}}',
      '',
      '## Quality Bar',
      '',
      'Would a senior professional pay $50 for this advice? If not, dig deeper.',
    ].join('\n'),
  },
  [PromptTemplate.QuickTipUser]: {
    name: 'quick-tip-user',
    type: 'text',
    fallback: [
      '## Task',
      '',
      'Create a personalized quick tip for this user. Return JSON only.',
      '',
      '## User Profile',
      '',
      '{{PROFILE_XML}}',
      '',
      '## Full Conversation Context',
      '',
      '{{CHAT_SUMMARY}}',
      '',
      '## Assessment Signals',
      '',
      '- Performance score: {{PERFORMANCE_SCORE}}',
      '- AI fluency: {{FLUENCY_LEVEL}}',
      '',
      '## Requirements',
      '',
      '- Search for cutting-edge techniques specific to their role and tools',
      '- The hook must create genuine curiosity without clickbait',
      "- The content must deliver on the hook's promise",
      '- Be specific: mention their actual tools, role, and use cases',
      '',
      'Return valid JSON with "hook" and "content" fields only.',
    ].join('\n'),
  },
  [PromptTemplate.VideoSegmentExtractionSystem]: {
    name: 'video-segment-extraction-system',
    type: 'text',
    fallback: [
      'You are analyzing a screen recording of an AI tool tutorial. Your task is to identify and describe EVERY user interaction with precise timestamps.',
      '',
      '## Your Task',
      '',
      'Watch the entire video carefully and identify ALL interactions including:',
      '- Mouse clicks (buttons, links, menus, dropdowns, checkboxes, etc.)',
      '- Text input (typing in fields, prompts, code editors)',
      '- Keyboard shortcuts',
      '- Scrolling actions (when significant)',
      '- Drag and drop actions',
      '- Hovering that reveals tooltips or menus',
      '- Any UI state changes triggered by the user',
      '',
      '## Output Format',
      '',
      'Return a valid JSON object with this exact structure:',
      '{',
      '  "tool_detected": "<Name of the AI tool being demonstrated>",',
      '  "ui_version": "<Any version indicators, UI layout description, or date markers visible>",',
      '  "segments": [',
      '    {',
      '      "id": "seg_001",',
      '      "start": 90.5,',
      '      "end": 95.0,',
      '      "description": "<Technical description with context>",',
      '      "metadata": {',
      '        "action_type": "click",',
      '        "ui_element": "model selector dropdown",',
      '        "feature_area": "model_selection",',
      '        "input_text": null,',
      '        "keyboard_shortcut": null,',
      '        "result_description": "Dropdown closes, pill now reads Opus 4.5",',
      '        "teaching_value": "How to switch between models for different tasks",',
      '        "skill_category": "model_selection",',
      '        "difficulty_level": "beginner"',
      '      }',
      '    }',
      '  ]',
      '}',
      '',
      '## CRITICAL: Timestamp Format',
      '',
      'Timestamps MUST be in SECONDS (not minutes). Examples:',
      '- 5 seconds into the video = 5.0',
      '- 1 minute 30 seconds = 90.0',
      '- 2 minutes 15 seconds = 135.0',
      '',
      'For a 2-minute video, the last timestamp should be around 120.0, NOT 2.0.',
      '',
      '## Description Guidelines',
      '',
      'Each description should be:',
      '1. **Technical**: Name the exact UI element (button name, menu item, field label)',
      '2. **Contextual**: Explain what the user is achieving with this action',
      '3. **Specific**: Include visible text, selected options, typed content when relevant',
      '',
      'Examples of good descriptions:',
      '- "Clicking the \'New Chat\' button in the top-left corner to start a fresh conversation"',
      '- "Opening the model selector dropdown and choosing \'Claude 3.5 Sonnet\' to switch from the default model"',
      '- "Typing a prompt in the message input field: \'Write a Python function to sort a list\'"',
      '- "Clicking the \'Copy\' button on the code block to copy the generated Python code to clipboard"',
      '- "Expanding the \'Advanced Settings\' accordion in the sidebar to access temperature controls"',
      '- "Adjusting the temperature slider from 0.7 to 0.3 for more deterministic outputs"',
      '',
      '## Metadata Fields (all required per segment)',
      '',
      '- action_type: "click" | "type" | "scroll" | "hover" | "drag" | "keyboard_shortcut" | "voice_input"',
      '- ui_element: Name of the UI element interacted with',
      '- feature_area: One of: "chat_input", "model_selection", "file_upload", "settings", "output_display", "code_editor", "prompt_library", "history", "sharing", "other"',
      '- input_text: Text typed or spoken (null if N/A)',
      '- keyboard_shortcut: Shortcut used (null if N/A)',
      '- result_description: What visually changed after the action',
      '- teaching_value: What this segment teaches (e.g. "How to upload files for analysis in Gemini")',
      '- skill_category: One of: "prompting", "model_selection", "file_handling", "output_formatting", "code_generation", "conversation_management", "settings_config", "collaboration", "automation", "evaluation", "safety", "multimodal", "context_management"',
      '- difficulty_level: "beginner" | "intermediate" | "advanced"',
      '',
      '## Segment Rules',
      '',
      '- ONE segment per atomic interaction (each click, each keystroke sequence, each selection)',
      '- Timestamps in float seconds. Min duration: {{MIN_SEGMENT_SECONDS}}s. Max duration: {{MAX_SEGMENT_SECONDS}}s',
      '- Sequential IDs: seg_001, seg_002, etc.',
      '- If the same area is clicked multiple times, create separate segments for each click',
      '- For typing, create one segment that covers the entire typing sequence for a single input field',
      '',
      '## Skip',
      '',
      '- Inactivity > 5 seconds (reading, waiting, idle). Note AI response generation as context in the NEXT interaction description, not as its own segment.',
      '- If a chunk has NO user interactions at all (e.g. user only reading), return "segments": [].',
      '',
      '## UX Version Detection',
      '',
      'Look for and report:',
      '- Version numbers anywhere in the UI',
      '- Tool branding and specific product names (e.g., "Gemini Advanced", "Claude Pro", "ChatGPT Plus")',
      '- UI layout characteristics that indicate a specific version or time period',
      '- Any visible dates or update indicators',
      '',
      '## Chunk Overlap',
      '',
      'When analyzing a time range that overlaps with adjacent chunks: include the full interaction with accurate absolute timestamps. Duplicate segments near boundaries are handled by the merge step.',
      '',
    ].join('\n'),
  },
  [PromptTemplate.VideoSegmentExtractionUser]: {
    name: 'video-segment-extraction-user',
    type: 'text',
    fallback: [
      'Analyze the provided video recording and extract ALL UI interaction segments.',
      '',
      'Video file: {{VIDEO_FILE_NAME}}',
      '{{TIME_RANGE_INSTRUCTION}}',
      '',
      'Important rules:',
      '- Every segment MUST include the full metadata object with all fields',
      '- Timestamps MUST be in seconds (float). Example: 1 minute 30 seconds = 90.0',
      '- If the time range contains no user interactions, return {"tool_detected": "...", "ui_version": "...", "segments": []}',
      '',
      'Return ONLY the JSON object, no additional text or markdown code fences.',
    ].join('\n'),
  },
  [PromptTemplate.VideoTeachingSegmentSystem]: {
    name: 'video-teaching-segment-system',
    type: 'text',
    fallback: [
      'You are analyzing a screen recording of an AI tool tutorial. Your task is to identify TEACHING SEGMENTS — coherent workflow demonstrations that show a complete concept or task being performed.',
      '',
      '## Your Task',
      '',
      'Watch the entire video and identify segments where the user demonstrates a meaningful workflow or concept. Each segment should:',
      '- Show a COMPLETE mini-workflow (not a single click)',
      '- Be useful as a standalone teaching clip embedded in a lesson',
      '- Last between {{MIN_SEGMENT_SECONDS}} and {{MAX_SEGMENT_SECONDS}} seconds',
      '',
      'Examples of good teaching segments:',
      '- "Writing a prompt, submitting it, and reviewing the AI response" (15-40s)',
      '- "Uploading a file, configuring analysis options, and getting results" (20-45s)',
      '- "Switching models, adjusting temperature, and comparing outputs" (10-30s)',
      '- "Creating a new project, setting parameters, and running first generation" (20-60s)',
      '',
      'DO NOT extract:',
      '- Individual clicks, hovers, or single UI interactions',
      '- Idle periods where the user is just reading',
      '- Segments shorter than {{MIN_SEGMENT_SECONDS}} seconds',
      '',
      '## Output Format',
      '',
      'Return a valid JSON object with this exact structure:',
      '{',
      '  "tool_detected": "<Name of the AI tool being demonstrated>",',
      '  "ui_version": "<Any version indicators, UI layout description, or date markers visible>",',
      '  "segments": [',
      '    {',
      '      "id": "seg_001",',
      '      "start": 12.0,',
      '      "end": 45.5,',
      '      "description": "<What workflow/concept this segment demonstrates>",',
      '      "metadata": {',
      '        "action_type": "workflow",',
      '        "ui_element": "chat interface + model selector",',
      '        "feature_area": "prompting",',
      '        "input_text": null,',
      '        "keyboard_shortcut": null,',
      '        "result_description": "User writes prompt, switches model, gets response, copies output",',
      '        "teaching_value": "End-to-end prompt workflow with model selection",',
      '        "skill_category": "prompting",',
      '        "difficulty_level": "beginner"',
      '      }',
      '    }',
      '  ]',
      '}',
      '',
      '## CRITICAL: Timestamp Format',
      '',
      'Timestamps MUST be in SECONDS (not minutes). Examples:',
      '- 5 seconds into the video = 5.0',
      '- 1 minute 30 seconds = 90.0',
      '- 2 minutes 15 seconds = 135.0',
      '',
      '## Description Guidelines',
      '',
      'Each description should explain:',
      '1. **What workflow** is being demonstrated (the sequence of actions)',
      '2. **What concept** the viewer learns from watching this segment',
      '3. **What outcome** the user achieves by the end of the segment',
      '',
      '## Metadata Fields (all required per segment)',
      '',
      '- action_type: "workflow" (always for teaching segments)',
      '- ui_element: Main UI areas involved (comma-separated if multiple)',
      '- feature_area: One of: "chat_input", "model_selection", "file_upload", "settings", "output_display", "code_editor", "prompt_library", "history", "sharing", "other"',
      '- input_text: Key text typed or spoken (null if N/A, summarize if long)',
      '- keyboard_shortcut: Shortcuts used (null if N/A)',
      '- result_description: What the user accomplished by end of segment',
      '- teaching_value: What a learner would gain from watching this segment',
      '- skill_category: One of: "prompting", "model_selection", "file_handling", "output_formatting", "code_generation", "conversation_management", "settings_config", "collaboration", "automation", "evaluation", "safety", "multimodal", "context_management"',
      '- difficulty_level: "beginner" | "intermediate" | "advanced"',
      '',
      '## Segment Rules',
      '',
      '- ONE segment per coherent workflow/concept demonstration',
      '- Timestamps in float seconds. Min duration: {{MIN_SEGMENT_SECONDS}}s. Max duration: {{MAX_SEGMENT_SECONDS}}s',
      '- Sequential IDs: seg_001, seg_002, etc.',
      '- Prefer fewer, higher-quality segments over many short ones',
      '- Segments may overlap slightly if they demonstrate different concepts',
      '',
      '## Skip',
      '',
      '- Inactivity > 5 seconds (reading, waiting, idle)',
      '- If a chunk has NO teaching-worthy workflows, return "segments": []',
      '',
      '## Chunk Overlap',
      '',
      'When analyzing a time range that overlaps with adjacent chunks: include the full workflow with accurate absolute timestamps. Duplicate segments near boundaries are handled by the merge step.',
      '',
    ].join('\n'),
  },
  [PromptTemplate.VideoTeachingSegmentUser]: {
    name: 'video-teaching-segment-user',
    type: 'text',
    fallback: [
      'Analyze the provided video recording and extract TEACHING SEGMENTS — coherent workflow demonstrations suitable for embedding in lessons.',
      '',
      'Video file: {{VIDEO_FILE_NAME}}',
      '{{TIME_RANGE_INSTRUCTION}}',
      '',
      'Important rules:',
      '- Extract workflows, NOT individual clicks. Each segment should show a complete mini-task.',
      '- Every segment MUST include the full metadata object with all fields',
      '- Timestamps MUST be in seconds (float). Example: 1 minute 30 seconds = 90.0',
      '- If the time range contains no teaching-worthy workflows, return {"tool_detected": "...", "ui_version": "...", "segments": []}',
      '',
      'Return ONLY the JSON object, no additional text or markdown code fences.',
    ].join('\n'),
  },
};
