/**
 * A9 Composer — deterministic page sequence per age bracket (2026-04-16 spec).
 *
 * Each age bracket produces a FIXED sequence of PDF pages. Some pages are
 * illustrations (full-bleed), some are text (prose from a beat), and some
 * are structural (cover, title, parent card, colophon).
 *
 * Beats with two illustrations (.1/.2) split their `text_pl` across two text
 * pages at a natural paragraph break near the midpoint. Single-illustration
 * beats (B2, B3, B6) get one text page.
 */

import type { AgeBracket } from './ageBracket';

export type PageKind =
  | 'cover'
  | 'blank'
  | 'title'
  | 'chapter_header'
  | 'mood_opening'
  | 'mood_closing'
  | 'illustration'
  | 'text'
  | 'parent_card'
  | 'colophon';

export interface PageSpec {
  pageNumber: number; // 1-indexed
  kind: PageKind;
  illustrationId?: string; // for kind=illustration/mood_opening/mood_closing/cover
  beatId?: string; // for kind=text/chapter_header
  /** When a beat is split across multiple text pages: 1..N. Omitted when N=1. */
  textPart?: number;
  /** Total parts in the beat this page belongs to — handy for "last part" checks. */
  textPartCount?: number;
  /** Chapter header title (kind === 'chapter_header'). Optional. */
  title?: string;
}

export interface SequenceOptions {
  /** Use one blank page after cover instead of two (DTP Lab default off). */
  singleBlankAfterCover?: boolean;
  /** Insert a chapter_header page before each beat (DTP Lab). */
  chapterHeaders?: boolean;
  /** Map beatId → chapter title to render on chapter_header pages. */
  chapterTitles?: Record<string, string>;
}

interface BeatLayout {
  beatId: string;
  illustrationIds: string[]; // 1 or 2 ids, in order
}

/** Per-bracket beat→illustration mapping (derived from A5 spec). */
function beatLayout(bracket: AgeBracket): BeatLayout[] {
  switch (bracket) {
    case '3-5':
      return [
        { beatId: '1', illustrationIds: ['scene_1.1', 'scene_1.2'] },
        { beatId: '2', illustrationIds: ['scene_2'] },
        { beatId: '3', illustrationIds: ['scene_3'] },
        { beatId: '4', illustrationIds: ['scene_4.1', 'scene_4.2'] },
        { beatId: '5', illustrationIds: ['scene_5.1', 'scene_5.2'] },
        { beatId: '6', illustrationIds: ['scene_6'] },
      ];
    case '6-8':
      return [
        { beatId: '1', illustrationIds: ['scene_1.1', 'scene_1.2'] },
        { beatId: '2', illustrationIds: ['scene_2'] },
        { beatId: '3', illustrationIds: ['scene_3'] },
        { beatId: '4', illustrationIds: ['scene_4.1', 'scene_4.2'] },
        { beatId: '4a', illustrationIds: ['scene_4a.1', 'scene_4a.2'] },
        { beatId: '5', illustrationIds: ['scene_5.1', 'scene_5.2'] },
        { beatId: '6', illustrationIds: ['scene_6'] },
      ];
    case '9+':
      return [
        { beatId: '1', illustrationIds: ['scene_1.1', 'scene_1.2'] },
        { beatId: '2', illustrationIds: ['scene_2'] },
        { beatId: '3', illustrationIds: ['scene_3'] },
        { beatId: '4', illustrationIds: ['scene_4.1', 'scene_4.2'] },
        { beatId: '4a', illustrationIds: ['scene_4a.1', 'scene_4a.2'] },
        { beatId: '4b', illustrationIds: ['scene_4b.1', 'scene_4b.2'] },
        { beatId: '5', illustrationIds: ['scene_5.1', 'scene_5.2'] },
        { beatId: '6', illustrationIds: ['scene_6'] },
      ];
  }
}

/**
 * Build the full deterministic page sequence for the given bracket.
 * Default page counts: 24 (3-5), 27 (6-8), 31 (9+).
 *
 * `partsPerBeat` (optional) maps beatId → number of text pages that beat
 * needs. When omitted, a beat with one illustration gets one text page,
 * a beat with two illustrations gets two — matching the original spec.
 * Pass a higher count when the beat's prose exceeds a single page.
 */
export function buildPageSequence(
  bracket: AgeBracket,
  partsPerBeat?: Map<string, number>,
  options?: SequenceOptions,
): PageSpec[] {
  const pages: Omit<PageSpec, 'pageNumber'>[] = [];

  pages.push({ kind: 'cover', illustrationId: 'cover' });
  // Default (production): two blanks — back-of-cover + facing-page for title
  // so spread #2 reads blank | title.
  // DTP Lab opt-in: one blank only — title page lands on the LEFT of spread
  // #2, opposite the first chapter_header. Tighter book-block opening.
  pages.push({ kind: 'blank' });
  if (!options?.singleBlankAfterCover) {
    pages.push({ kind: 'blank' });
  }
  pages.push({ kind: 'title' });
  // mood_opening dropped — having an extra illustration between title and
  // the first beat broke the illus | text rhythm. The asset is still
  // generated by A7; it just isn't placed in the PDF anymore.

  for (const beat of beatLayout(bracket)) {
    if (options?.chapterHeaders) {
      pages.push({
        kind: 'chapter_header',
        beatId: beat.beatId,
        title: options.chapterTitles?.[beat.beatId],
      });
    }
    // When the caller passed a partsPerBeat map (typst-render path via
    // buildRenderBrief) we honor that count exactly — including the case
    // where a 2-illustration beat needs only one text page. Without a map
    // (legacy pdfkit composer) we fall back to the original spec where
    // illustration count == text-page count.
    const requested = partsPerBeat?.get(beat.beatId) ?? beat.illustrationIds.length;
    const parts = Math.max(1, requested);
    const splitTextPage = (part: number): Omit<PageSpec, 'pageNumber'> => ({
      kind: 'text',
      beatId: beat.beatId,
      textPart: parts > 1 ? part : undefined,
      textPartCount: parts > 1 ? parts : undefined,
    });

    if (beat.illustrationIds.length === 1) {
      pages.push({ kind: 'illustration', illustrationId: beat.illustrationIds[0] });
      for (let i = 1; i <= parts; i++) pages.push(splitTextPage(i));
    } else if (parts === 1) {
      // 2 illustrations + single text page → sandwich: illus1, text, illus2.
      pages.push({ kind: 'illustration', illustrationId: beat.illustrationIds[0] });
      pages.push(splitTextPage(1));
      pages.push({ kind: 'illustration', illustrationId: beat.illustrationIds[1] });
    } else {
      // 2 illustrations + multiple text pages — distribute around them, with
      // any odd-numbered remainder going BEFORE the second illustration.
      const before = Math.ceil(parts / 2);
      const after = parts - before;
      pages.push({ kind: 'illustration', illustrationId: beat.illustrationIds[0] });
      for (let i = 1; i <= before; i++) pages.push(splitTextPage(i));
      pages.push({ kind: 'illustration', illustrationId: beat.illustrationIds[1] });
      for (let i = 1; i <= after; i++) pages.push(splitTextPage(before + i));
    }
  }

  pages.push({ kind: 'mood_closing', illustrationId: 'mood_closing' });
  pages.push({ kind: 'parent_card' });
  pages.push({ kind: 'colophon' });

  return pages.map((p, i) => ({ pageNumber: i + 1, ...p }));
}

/**
 * Split a beat's prose into two roughly-balanced halves for .1/.2 layout.
 * Prefers a natural paragraph break near the midpoint. Falls back to a
 * sentence-level split, and finally to a word-count split if all else fails.
 */
export function splitBeatText(text: string): [string, string] {
  const trimmed = text.trim();
  if (!trimmed) return ['', ''];

  // Try paragraph split (double newline) closest to midpoint
  const paragraphs = trimmed
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);
  if (paragraphs.length >= 2) {
    const totalLen = paragraphs.reduce((sum, p) => sum + p.length, 0);
    let acc = 0;
    let bestIdx = 1;
    let bestDelta = Infinity;
    for (let i = 1; i < paragraphs.length; i++) {
      acc += paragraphs[i - 1].length;
      const delta = Math.abs(acc - totalLen / 2);
      if (delta < bestDelta) {
        bestDelta = delta;
        bestIdx = i;
      }
    }
    return [paragraphs.slice(0, bestIdx).join('\n\n'), paragraphs.slice(bestIdx).join('\n\n')];
  }

  // Sentence split
  const sentences = trimmed.match(/[^.!?]+[.!?]+\s*/g);
  if (sentences && sentences.length >= 2) {
    const totalLen = trimmed.length;
    let acc = 0;
    let splitIdx = Math.ceil(sentences.length / 2);
    for (let i = 1; i < sentences.length; i++) {
      acc += sentences[i - 1].length;
      if (acc >= totalLen / 2) {
        splitIdx = i;
        break;
      }
    }
    return [
      sentences.slice(0, splitIdx).join('').trim(),
      sentences.slice(splitIdx).join('').trim(),
    ];
  }

  // Word-count split (last resort — single sentence, single paragraph)
  const words = trimmed.split(/\s+/);
  if (words.length < 2) return [trimmed, ''];
  const mid = Math.floor(words.length / 2);
  return [words.slice(0, mid).join(' '), words.slice(mid).join(' ')];
}

/**
 * Approx character budget per page. Sized for the production single-A4
 * portrait format (the booklet A5 mode is now opt-in); A4 single has ~67%
 * more text area than the booklet A5 page, so budgets are raised
 * accordingly. The Typst template still applies a small font-shrink
 * fallback for outlier paragraphs.
 */
export function charBudgetFor(bracket: AgeBracket): number {
  // Skalibrowane 31.07.2026 na geometrii po poprawkach DTP (margines 44pt,
  // interlinia 0.59em ≈ 130%). Binary search po długości tekstu w Typście:
  // maksimum bez uruchomienia auto-shrinku czcionki to odpowiednio 762 / 1158
  // / 1527 znaków — bierzemy ~92% tego zapasu, bo łamanie zależy od tego, jak
  // wypadną konkretne słowa. Poprzednie wartości (1000/1500/1800) pochodziły
  // z ciaśniejszego składu i tak przekraczały budżet, że każda strona tekstu
  // renderowała się na najmniejszej czcionce z pięciu prób.
  if (bracket === '3-5') return 700;
  if (bracket === '6-8') return 1080;
  return 1420;
}

/**
 * Pack a beat's prose into N chunks, each ≤ charBudget characters.
 * Greedy: keeps paragraphs together when they fit; splits long paragraphs
 * on sentence boundaries; falls back to whole-paragraph emission when a
 * single sentence exceeds the budget (Typst still renders, font-shrink
 * fallback handles the squeeze).
 *
 * Always returns at least one element. For text within budget, returns
 * `[text]` — caller can treat that as a single text page.
 */
export function splitBeatTextDynamic(text: string, charBudget: number): string[] {
  const trimmed = text.trim();
  if (!trimmed) return [''];
  if (trimmed.length <= charBudget) return [trimmed];

  const paragraphs = trimmed
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);

  // Atomize: each atom is one paragraph (small enough) or one sentence
  // (when paragraph alone exceeds budget). Keeping atoms maximally large
  // produces more natural breaks than always splitting per sentence.
  const atoms: string[] = [];
  for (const p of paragraphs) {
    if (p.length <= charBudget) {
      atoms.push(p);
      continue;
    }
    const sentences = p.match(/[^.!?]+[.!?]+(\s+|$)/g);
    if (!sentences || sentences.length === 0) {
      atoms.push(p);
      continue;
    }
    let buf = '';
    for (const s of sentences) {
      const candidate = buf ? buf + s : s;
      if (candidate.length <= charBudget) {
        buf = candidate;
      } else {
        if (buf) atoms.push(buf.trim());
        buf = s;
      }
    }
    if (buf.trim()) atoms.push(buf.trim());
  }

  // Pack atoms into chunks separated by blank lines.
  const pack = (budget: number): string[] => {
    const out: string[] = [];
    let cur = '';
    for (const atom of atoms) {
      const candidate = cur ? cur + '\n\n' + atom : atom;
      if (!cur || candidate.length <= budget) {
        cur = candidate;
      } else {
        out.push(cur);
        cur = atom;
      }
    }
    if (cur) out.push(cur);
    return out;
  };

  const greedy = pack(charBudget);
  if (greedy.length <= 1) return greedy.length > 0 ? greedy : [trimmed];

  // Balance: avoid a tiny last chunk (which prints as a near-empty page) by
  // repacking against a budget = ceil(total / chunk-count). Same chunk count,
  // chars distributed more evenly across pages.
  const totalChars = atoms.reduce((s, a) => s + a.length, 0);
  const balanced = pack(Math.ceil(totalChars / greedy.length));
  // If balancing somehow produced fewer chunks (atoms+separators math edge),
  // keep the more conservative greedy result.
  return balanced.length === greedy.length ? balanced : greedy;
}
